name: pokards
description: A mobile/web/desktop app built with Flutter to play the role of the dealer in a Poker Texas hold'em game.
publish_to: 'none'

version: 1.0.1+2

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  auto_route: ^1.0.2
  crypto: ^3.0.1
  fluttericon: ^2.0.0
  freezed_annotation: ^0.14.0
  get_it: ^6.0.0
  flutter_markdown: ^0.6.1
  google_fonts: ^2.0.0
  injectable: ^1.2.0
  url_launcher: ^6.0.3
  keyboard_dismisser: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: 1.0.2
  build_runner: null
  freezed: ^0.14.0+1
  injectable_generator: ^1.2.0
  lint: ^1.5.3
  flutter_native_splash: ^1.1.7+1

flutter_native_splash:
  color: '#ef5350'
  color_dark: '#616161'
  image: assets/tidann_dev.png

flutter:
  uses-material-design: true
  assets:
    - assets/help.md
    - assets/about.md
    